services:
  adminer:
    image: adminer:5.1.0
    hostname: adminer
    #volumes:
    #  - ${APPS_DIR}/adminer/login-servers.php:/var/www/html/plugins-enabled/login-servers.php
    networks:
      - proxy2
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_SERVERS={
          "web1-postgres":{
            "driver":"pgsql",
            "server":"postgres",
            "username":"postgres",
            "password":"${POSTGRES_PASSWORD}",
            "db":""
          },
          "web1-mysql":{
            "driver":"server",
            "server":"mysql",
            "username":"root",
            "password":"${MYSQL_PASSWORD}",
            "db":""
          },
          "neon-postgres":{
            "driver":"pgsql",
            "server":"ep-delicate-field-acb9tkzb-pooler.sa-east-1.aws.neon.tech",
            "username":"neondb_owner",
            "password":"${NEONPG_PASSWORD}",
            "db":"aitools"
          }
        }

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.adminer.rule=Host(`dba.$DOMAINNAME2`)
        - traefik.http.services.adminer.loadbalancer.server.port=8080
        - traefik.http.routers.adminer.middlewares=tinyauth

networks:
  proxy2:
    external: true
    attachable: true
    name: proxy2