services:
  linkding:
    image: sissbruecker/linkding:latest
    hostname: linkding
    volumes:
      - linkding:/etc/linkding/data
    networks:
      - proxy2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.linkding.rule=Host(`linkding.$DOMAINNAME2`)
        - traefik.http.services.linkding.loadbalancer.server.port=9090
        #- traefik.http.routers.linkding.middlewares=traefik-forward-auth

networks:
  proxy2:
    external: true
    attachable: true
    name: proxy2

volumes:
  linkding:
    #external: true
    name: linkding