services:
  traefik:
    image: traefik:v3
    hostname: traefik
    ports:
      # listen on host ports without ingress network
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - proxy
      - proxy2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APPS_DIR}/traefik:/traefik
      #- /var/log:/var/log
    command:
      - --api.dashboard=true
      - --api.insecure=true # abrir o dashboard na porta 8080
      - --log.level=INFO
      #- --log.filepath=/var/log/traefik.log
      - --accesslog=true
      #- --accesslog.filepath=/var/log/traefik-access.log
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.network=proxy
      # files provider...
      - --providers.file.watch=true
      - --providers.file.directory=/traefik/rules
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.asDefault=true
      - --entrypoints.websecure.http.tls.certresolver=${RESOLVER_DEFAULT}
      # optionally create wildcard cert, without LE will create TLS certs for all `Host()`s
      - --entrypoints.websecure.http.tls.domains[0].main=${DOMAINNAME2}
      - --entrypoints.websecure.http.tls.domains[0].sans=*.${DOMAINNAME2}
      #- --entrypoints.websecure.http.tls.domains[1].main=${DOMAINNAME1}
      #- --entrypoints.websecure.http.tls.domains[1].sans=*.${DOMAINNAME1}
      # resolver DNS-01
      - --certificatesresolvers.dns.acme.email=${RESOLVER1_EMAIL}
      - --certificatesresolvers.dns.acme.storage=/traefik/certs/acme-dns.json
      - --certificatesresolvers.dns.acme.dnschallenge.provider=${RESOLVER1_PROVIDER}
      # Opcional: se quiser resolvers customizados para DNS (ajuda propagação lenta no Cloudflare)
      - --certificatesresolvers.dns.acme.dnschallenge.resolvers=${RESOLVER1_DNS}
      - --certificatesresolvers.dns.acme.dnschallenge.propagation.delaybeforechecks=30s
      - --certificatesresolvers.dns.acme.caserver=${RESOLVER1_URL}
      # resolver DNS-02
      - --certificatesresolvers.dns2.acme.email=${RESOLVER2_EMAIL}
      - --certificatesresolvers.dns2.acme.storage=/traefik/certs/acme-dns2.json
      - --certificatesresolvers.dns2.acme.dnschallenge.provider=${RESOLVER2_PROVIDER}
      - --certificatesresolvers.dns2.acme.dnschallenge.resolvers=${RESOLVER2_DNS}
      - --certificatesresolvers.dns2.acme.dnschallenge.propagation.delaybeforechecks=30s
      - --certificatesresolvers.dns2.acme.caserver=${RESOLVER2_URL}
      # resolver HTTP-01
      - --certificatesresolvers.http.acme.email=${RESOLVERHTTP_EMAIL}
      - --certificatesresolvers.http.acme.storage=/traefik/certs/acme-http.json
      - --certificatesresolvers.http.acme.httpchallenge=true
      - --certificatesresolvers.http.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.http.acme.caserver=${RESOLVERHTTP_URL}

    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - DYNU_API_KEY=${DYNU_API_KEY}
      - DOMAINNAME1=${DOMAINNAME1}
      - DOMAINNAME2=${DOMAINNAME2}
      - DOMAINNAME3=${DOMAINNAME3}

    deploy:
      #mode: global
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.mydashboard.rule=Host(`proxy.$DOMAINNAME2`)
        - traefik.http.routers.mydashboard.service=api@internal
        - traefik.http.routers.mydashboard.middlewares=tinyauth
        - traefik.http.services.mydashboard.loadbalancer.server.port=8080
        - traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik
        #- traefik.http.middlewares.tinyauth.forwardauth.authResponseHeaders=X-Forwarded-User
        - traefik.http.middlewares.tinyauth.forwardauth.authResponseHeaders=Remote-User,Remote-Email,Remote-Groups

  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5
    hostname: tinyauth
    networks:
      - proxy
      - proxy2
    volumes:
      - tinyauth:/data
    environment:
      - TINYAUTH_APPURL=https://auth.$DOMAINNAME2
      - TINYAUTH_AUTH_USERS=${TINYAUTH_AUTH_USERS}
      # google oauth
      - TINYAUTH_OAUTH_WHITELIST=${TINYAUTH_OAUTH_WHITELIST}
      - TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID=${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID}
      - TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET=${TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.tinyauth.rule=Host(`auth.$DOMAINNAME2`)
        - traefik.http.services.tinyauth.loadbalancer.server.port=3000
        #- traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik

volumes:
  tinyauth:
    name: tinyauth

networks:
  proxy:
    external: true
    attachable: true
    name: proxy
  proxy2:
    external: true
    attachable: true
    name: proxy2